import type { Statute } from './types';
import { AGENCY_IDOL, AGENCY_IDHR, AGENCY_OSHA, AGENCY_NLRB, AGENCY_EEOC } from '../agency-filings';

export const ILLINOIS_STATUTES: Statute[] = [
  // 1. Illinois Whistleblower Act
  {
    id: 'illinois-whistleblower-act',
    name: 'Illinois Whistleblower Act',
    citation: '740 ILCS 174',
    category: 'whistleblower',
    triggerTags: ['whistleblower', 'retaliation_for_reporting', 'reported_violations', 'internal_complaint'],
    employerSizeMin: 0,
    employerTypes: ['any'],
    geographies: ['illinois'],
    workerTypes: ['employee'],
    feeShifting: true,
    solDays: 365,
    docBonus: 10,
  },
  // 2. Illinois Human Rights Act
  {
    id: 'illinois-human-rights-act',
    name: 'Illinois Human Rights Act',
    citation: '775 ILCS 5',
    category: 'discrimination',
    triggerTags: ['discrimination', 'harassment', 'hostile_work_environment', 'sexual_harassment', 'race_discrimination', 'age_discrimination', 'disability_discrimination', 'pregnancy_discrimination', 'religion_discrimination'],
    employerSizeMin: 1,
    employerTypes: ['any'],
    geographies: ['illinois'],
    workerTypes: ['employee', 'contractor'],
    protectedCharacteristics: ['race', 'color', 'religion', 'sex', 'national_origin', 'ancestry', 'citizenship_status', 'age', 'marital_status', 'disability', 'military_status', 'sexual_orientation', 'gender_identity', 'pregnancy', 'order_of_protection', 'unfavorable_military_discharge'],
    feeShifting: true,
    solDays: 300,
    agencyFiling: AGENCY_IDHR,
    docBonus: 10,
  },
  // 3. Illinois Wage Payment and Collection Act
  {
    id: 'illinois-wage-payment-collection-act',
    name: 'Illinois Wage Payment and Collection Act',
    citation: '820 ILCS 115',
    category: 'wage_theft',
    triggerTags: ['unpaid_wages', 'final_paycheck', 'withheld_wages', 'wage_deductions', 'late_payment', 'commission_dispute'],
    employerSizeMin: 0,
    employerTypes: ['any'],
    geographies: ['illinois'],
    workerTypes: ['employee'],
    feeShifting: true,
    solDays: 3650,
    agencyFiling: AGENCY_IDOL,
    docBonus: 15,
  },
  // 4. Illinois Minimum Wage Law
  {
    id: 'illinois-minimum-wage-law',
    name: 'Illinois Minimum Wage Law',
    citation: '820 ILCS 105',
    category: 'wage_theft',
    triggerTags: ['minimum_wage', 'below_minimum_wage', 'overtime', 'unpaid_overtime', 'tip_credit'],
    employerSizeMin: 0,
    employerTypes: ['any'],
    geographies: ['illinois'],
    workerTypes: ['employee'],
    feeShifting: true,
    solDays: 1095,
    agencyFiling: AGENCY_IDOL,
    docBonus: 10,
  },
  // 5. One Day Rest in Seven Act
  {
    id: 'illinois-one-day-rest-in-seven-act',
    name: 'Illinois One Day Rest in Seven Act',
    citation: '820 ILCS 140',
    category: 'wage_theft',
    triggerTags: ['no_day_off', 'no_rest_day', 'no_meal_break', 'seven_day_work_week'],
    employerSizeMin: 0,
    employerTypes: ['any'],
    geographies: ['illinois'],
    workerTypes: ['employee'],
    feeShifting: false,
    solDays: 1095,
    agencyFiling: AGENCY_IDOL,
    docBonus: 5,
  },
  // 6. Employee Classification Act
  {
    id: 'illinois-employee-classification-act',
    name: 'Illinois Employee Classification Act',
    citation: '820 ILCS 185',
    category: 'wage_theft',
    triggerTags: ['misclassification', 'independent_contractor_misclassification', '1099_should_be_w2'],
    employerSizeMin: 0,
    employerTypes: ['private'],
    geographies: ['illinois'],
    workerTypes: ['contractor'],
    feeShifting: true,
    solDays: 1825,
    agencyFiling: AGENCY_IDOL,
    docBonus: 10,
  },
  // 7. Illinois Equal Pay Act
  {
    id: 'illinois-equal-pay-act',
    name: 'Illinois Equal Pay Act',
    citation: '820 ILCS 112',
    category: 'discrimination',
    triggerTags: ['pay_disparity', 'unequal_pay', 'gender_pay_gap', 'race_pay_gap', 'salary_discrimination'],
    employerSizeMin: 0,
    employerTypes: ['any'],
    geographies: ['illinois'],
    workerTypes: ['employee'],
    protectedCharacteristics: ['sex', 'race', 'african_american'],
    feeShifting: true,
    solDays: 1825,
    agencyFiling: AGENCY_IDOL,
    docBonus: 15,
  },
  // 8. Workplace Transparency Act
  {
    id: 'illinois-workplace-transparency-act',
    name: 'Illinois Workplace Transparency Act',
    citation: '820 ILCS 96',
    category: 'discrimination',
    triggerTags: ['nda_retaliation', 'forced_arbitration', 'non_disclosure_retaliation', 'confidentiality_clause_abuse'],
    employerSizeMin: 0,
    employerTypes: ['any'],
    geographies: ['illinois'],
    workerTypes: ['employee'],
    feeShifting: false,
    solDays: 365,
    docBonus: 10,
  },
  // 9. Victims' Economic Security and Safety Act (VESSA)
  {
    id: 'illinois-vessa',
    name: "Victims' Economic Security and Safety Act",
    citation: '820 ILCS 180',
    category: 'leave',
    triggerTags: ['domestic_violence_leave', 'victim_leave', 'sexual_violence_leave', 'stalking_leave'],
    employerSizeMin: 1,
    employerTypes: ['any'],
    geographies: ['illinois'],
    workerTypes: ['employee'],
    feeShifting: true,
    solDays: 365,
    docBonus: 5,
  },
  // 10. Child Bereavement Leave Act
  {
    id: 'illinois-child-bereavement-leave-act',
    name: 'Illinois Child Bereavement Leave Act',
    citation: '820 ILCS 154',
    category: 'leave',
    triggerTags: ['bereavement_leave', 'child_loss_leave', 'denied_bereavement'],
    employerSizeMin: 50,
    employerTypes: ['any'],
    geographies: ['illinois'],
    workerTypes: ['employee'],
    feeShifting: false,
    solDays: 365,
    docBonus: 5,
  },
  // 11. Family Military Leave Act
  {
    id: 'illinois-family-military-leave-act',
    name: 'Illinois Family Military Leave Act',
    citation: '820 ILCS 151',
    category: 'leave',
    triggerTags: ['military_leave', 'military_family_leave', 'deployment_leave'],
    employerSizeMin: 15,
    employerTypes: ['any'],
    geographies: ['illinois'],
    workerTypes: ['employee'],
    feeShifting: false,
    solDays: 365,
    docBonus: 5,
  },
  // 12. School Visitation Rights Act
  {
    id: 'illinois-school-visitation-rights-act',
    name: 'Illinois School Visitation Rights Act',
    citation: '820 ILCS 147',
    category: 'leave',
    triggerTags: ['school_visitation', 'school_meeting_leave', 'parent_school_leave'],
    employerSizeMin: 50,
    employerTypes: ['any'],
    geographies: ['illinois'],
    workerTypes: ['employee'],
    feeShifting: false,
    solDays: 365,
    docBonus: 5,
  },
  // 13. Personnel Record Review Act
  {
    id: 'illinois-personnel-record-review-act',
    name: 'Illinois Personnel Record Review Act',
    citation: '820 ILCS 40',
    category: 'privacy',
    triggerTags: ['personnel_file_denied', 'records_request_denied', 'employee_records'],
    employerSizeMin: 5,
    employerTypes: ['any'],
    geographies: ['illinois'],
    workerTypes: ['employee'],
    feeShifting: true,
    solDays: 365,
    docBonus: 5,
  },
  // 14. Right to Privacy in the Workplace Act
  {
    id: 'illinois-right-to-privacy-workplace-act',
    name: 'Illinois Right to Privacy in the Workplace Act',
    citation: '820 ILCS 55',
    category: 'privacy',
    triggerTags: ['off_duty_conduct', 'social_media_retaliation', 'lawful_activity_retaliation'],
    employerSizeMin: 0,
    employerTypes: ['any'],
    geographies: ['illinois'],
    workerTypes: ['employee'],
    feeShifting: true,
    solDays: 365,
    docBonus: 5,
  },
  // 15. Biometric Information Privacy Act (BIPA)
  {
    id: 'illinois-bipa',
    name: 'Illinois Biometric Information Privacy Act',
    citation: '740 ILCS 14',
    category: 'privacy',
    triggerTags: ['biometric_data', 'fingerprint_scan', 'face_recognition', 'biometric_collection'],
    employerSizeMin: 0,
    employerTypes: ['any'],
    geographies: ['illinois'],
    workerTypes: ['any'],
    feeShifting: true,
    solDays: 1825,
    docBonus: 10,
  },
  // 16. Eavesdropping Act
  {
    id: 'illinois-eavesdropping-act',
    name: 'Illinois Eavesdropping Act',
    citation: '720 ILCS 5/14',
    category: 'privacy',
    triggerTags: ['recorded_without_consent', 'surveillance', 'eavesdropping', 'wiretapping'],
    employerSizeMin: 0,
    employerTypes: ['any'],
    geographies: ['illinois'],
    workerTypes: ['any'],
    feeShifting: true,
    solDays: 1825,
    docBonus: 5,
  },
  // 17. Workers' Compensation Act — Retaliation provision
  {
    id: 'illinois-workers-comp-retaliation',
    name: "Illinois Workers' Compensation Act (Retaliation)",
    citation: '820 ILCS 305/4(h)',
    category: 'retaliation',
    triggerTags: ['workers_comp_retaliation', 'fired_for_injury_claim', 'workers_comp_denial'],
    employerSizeMin: 0,
    employerTypes: ['any'],
    geographies: ['illinois'],
    workerTypes: ['employee'],
    feeShifting: false,
    solDays: 1095,
    docBonus: 10,
  },
  // 18. Illinois Occupational Safety and Health Act
  {
    id: 'illinois-osha',
    name: 'Illinois Occupational Safety and Health Act',
    citation: '820 ILCS 219',
    category: 'safety',
    triggerTags: ['unsafe_conditions', 'safety_complaint', 'osha_retaliation', 'safety_report_retaliation'],
    employerSizeMin: 0,
    employerTypes: ['any'],
    geographies: ['illinois'],
    workerTypes: ['employee'],
    feeShifting: false,
    solDays: 180,
    agencyFiling: AGENCY_OSHA,
    docBonus: 10,
  },
  // 19. Illinois Public Labor Relations Act
  {
    id: 'illinois-public-labor-relations-act',
    name: 'Illinois Public Labor Relations Act',
    citation: '5 ILCS 315',
    category: 'union_activity',
    triggerTags: ['union_activity', 'collective_bargaining', 'union_retaliation', 'organizing_retaliation'],
    employerSizeMin: 0,
    employerTypes: ['public', 'government'],
    geographies: ['illinois'],
    workerTypes: ['employee'],
    feeShifting: false,
    solDays: 180,
    docBonus: 5,
  },
  // 20. Prevailing Wage Act
  {
    id: 'illinois-prevailing-wage-act',
    name: 'Illinois Prevailing Wage Act',
    citation: '820 ILCS 130',
    category: 'wage_theft',
    triggerTags: ['prevailing_wage', 'public_works_wage', 'government_contract_wage'],
    employerSizeMin: 0,
    employerTypes: ['any'],
    geographies: ['illinois'],
    workerTypes: ['employee'],
    feeShifting: true,
    solDays: 1825,
    agencyFiling: AGENCY_IDOL,
    docBonus: 10,
  },
  // 21. Day and Temporary Labor Services Act
  {
    id: 'illinois-day-temp-labor-act',
    name: 'Illinois Day and Temporary Labor Services Act',
    citation: '820 ILCS 175',
    category: 'wage_theft',
    triggerTags: ['temp_worker', 'staffing_agency', 'day_labor', 'temp_agency_abuse'],
    employerSizeMin: 0,
    employerTypes: ['private'],
    geographies: ['illinois'],
    workerTypes: ['temp'],
    feeShifting: true,
    solDays: 1095,
    agencyFiling: AGENCY_IDOL,
    docBonus: 5,
  },
  // 22. Cook County Earned Sick Leave Ordinance
  {
    id: 'cook-county-earned-sick-leave',
    name: 'Cook County Earned Sick Leave Ordinance',
    citation: 'Cook County Code Ch. 42, Art. IX',
    category: 'leave',
    triggerTags: ['sick_leave_denied', 'no_sick_time', 'sick_leave_retaliation'],
    employerSizeMin: 0,
    employerTypes: ['any'],
    geographies: ['cook_county'],
    workerTypes: ['employee'],
    feeShifting: true,
    solDays: 1095,
    docBonus: 5,
  },
  // 23. Chicago Fair Workweek Ordinance
  {
    id: 'chicago-fair-workweek',
    name: 'Chicago Fair Workweek Ordinance',
    citation: 'Chicago Municipal Code 1-25',
    category: 'wage_theft',
    triggerTags: ['schedule_change', 'clopening', 'no_advance_schedule', 'on_call_abuse'],
    employerSizeMin: 100,
    employerTypes: ['private'],
    geographies: ['chicago'],
    workerTypes: ['employee'],
    feeShifting: true,
    solDays: 1095,
    docBonus: 5,
  },
  // 24. Chicago Anti-Retaliation Ordinance
  {
    id: 'chicago-anti-retaliation-ordinance',
    name: 'Chicago Anti-Retaliation Ordinance',
    citation: 'Chicago Municipal Code 6-140',
    category: 'retaliation',
    triggerTags: ['retaliation', 'fired_for_complaint', 'retaliation_for_exercising_rights'],
    employerSizeMin: 0,
    employerTypes: ['any'],
    geographies: ['chicago'],
    workerTypes: ['employee'],
    feeShifting: true,
    solDays: 365,
    docBonus: 5,
  },
  // 25. Title VII of the Civil Rights Act (federal)
  {
    id: 'title-vii-civil-rights',
    name: 'Title VII of the Civil Rights Act',
    citation: '42 U.S.C. § 2000e',
    category: 'discrimination',
    triggerTags: ['discrimination', 'harassment', 'hostile_work_environment', 'sexual_harassment', 'race_discrimination', 'religion_discrimination', 'national_origin_discrimination'],
    employerSizeMin: 15,
    employerTypes: ['any'],
    geographies: ['federal'],
    workerTypes: ['employee'],
    protectedCharacteristics: ['race', 'color', 'religion', 'sex', 'national_origin'],
    feeShifting: true,
    solDays: 300,
    agencyFiling: AGENCY_EEOC,
    docBonus: 10,
  },
  // 26. Fair Labor Standards Act (federal)
  {
    id: 'flsa',
    name: 'Fair Labor Standards Act',
    citation: '29 U.S.C. § 201',
    category: 'wage_theft',
    triggerTags: ['unpaid_overtime', 'minimum_wage', 'misclassification', 'off_the_clock', 'overtime'],
    employerSizeMin: 0,
    employerTypes: ['any'],
    geographies: ['federal'],
    workerTypes: ['employee'],
    feeShifting: true,
    solDays: 730,
    agencyFiling: AGENCY_IDOL,
    docBonus: 10,
  },
  // 27. National Labor Relations Act (federal)
  {
    id: 'nlra',
    name: 'National Labor Relations Act',
    citation: '29 U.S.C. § 151',
    category: 'union_activity',
    triggerTags: ['union_activity', 'concerted_activity', 'organizing', 'union_retaliation', 'collective_bargaining'],
    employerSizeMin: 0,
    employerTypes: ['private'],
    geographies: ['federal'],
    workerTypes: ['employee'],
    feeShifting: false,
    solDays: 180,
    agencyFiling: AGENCY_NLRB,
    docBonus: 5,
  },
];
